---
- hosts: webserver
  become: "true"
  gather_facts: yes
  become_method: sudo
  roles:
    - Application

- hosts: database
  become: yes
  gather_facts: yes
  become_method: sudo
  roles:
    - Application
